# version: '3.8'

# services:

#   avionics:
#     build: ./avionics
#     networks:
#       - internal
#     ports: []
#     restart: unless-stopped

#   pilot_interface:
#     build: ./pilot_interface
#     networks:
#       - internal
#     ports:
#       - "8080:80"
#     depends_on:
#       - avionics
#     restart: unless-stopped

#   maintenance_server:
#     build: ./maintenance_server
#     networks:
#       - internal
#     ports:
#       - "5000:5000"
#     depends_on:
#       - avionics
#     restart: unless-stopped

#   ife_server:
#     build: ./ife_server
#     networks:
#       - public
#     ports:
#       - "8081:80"
#     restart: unless-stopped

#   passenger_device:
#     build: ./passenger_device
#     networks:
#       - public
#     depends_on:
#       - ife_server
#     restart: "no"

#   secure_gateway:
#     build: ./secure_gateway
#     networks:
#       - internal
#       - public
#     ports:
#       - "8443:443"
#     restart: unless-stopped

#   sensors:
#     build: ./sensors
#     networks: [ internal ]

#   controllers:
#     build: ./controllers
#     networks: [ internal ]

#   actuators:
#     build: ./actuators
#     networks: [ internal ]

# networks:
#   internal:
#     driver: bridge
#   public:
#     driver: bridge



version: '3.8'

services:
  # для mqtt
  mosquitto-broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-broker
    networks:
      - avionics_bus
    ports:
      - "1883:1883"      # MQTT
      - "9001:9001"      # WebSocket (если надо)
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

  # 🧠 Центральный авиационный модуль
  # Взаимодействие по "псевдо-CAN" (через UDP)
  avionics:
    build: ./avionics
    networks:
      - avionics_bus
    ports: []
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mosquitto-broker
      - secure_gateway
    restart: unless-stopped

  # 🧑‍✈️ Интерфейс пилота — доступ к телеметрии и управлению
  # Протокол: HTTP (порт 80), соединён с avionics и шлюзом
  pilot_interface:
    build: ./pilot_interface
    networks:
      - avionics_bus      # CAN-подобная сеть
      - control_network   # служебная внутренняя сеть
    ports:
      - "8080:80"          # HTTP — УЯЗВИМ!
    depends_on:
      - avionics
    #restart: unless-stopped

  # 🧰 Технический сервер для обслуживания и логов
  # Протокол: HTTP API (Flask), DEBUG-режим
  maintenance_server:
    build: ./maintenance_server
    networks:
      - control_network
    ports:
      - "5000:5000"        # HTTP API — УЯЗВИМ!
    environment:
      - DEBUG=True         # УЯЗВИМОСТЬ: позволяет удалённое выполнение кода
    depends_on:
      - avionics
    #restart: unless-stopped

  # 🎬 IFE-сервер (In-Flight Entertainment) для пассажиров
  # Протокол: HTTP (порт 80), доступен из публичной сети
  ife_server:
    build: ./ife_server
    networks:
      - public_access
    ports:
      - "8081:80"         # HTTP — УЯЗВИМ!
    #restart: unless-stopped

  # 📱 Устройство пассажира — клиент IFE-сервиса
  # Протокол: HTTP, доступ к ife_server
  passenger_device:
    build: ./passenger_device
    networks:
      - public_access
    depends_on:
      - ife_server
    #restart: "no"

  # 🔐 Защищённый шлюз — точка перехода между сетями
  # Протоколы: HTTPS (8443), маршрутизация и фильтрация
  secure_gateway:
    build: ./secure_gateway
    networks:
      - public_access      # пассажирская сеть
      - control_network    # внутренняя служебная
      - avionics_bus       # CAN/UDP сеть
    environment:
      - PYTHONUNBUFFERED=1  # Вывод логов в реальном времени
    ports:
      - "8443:443"         # HTTPS — безопасный протокол
    volumes:
      - ./secure_gateway/server.crt:/app/server.crt
      - ./secure_gateway/server.key:/app/server.key # Монтируем сертификаты
    depends_on:
      - mosquitto-broker
    #restart: unless-stopped

  # 📡 Сенсоры — отправляют телеметрию (температура, давление и т.д.)
  # Протокол: псевдо-CAN через UDP, вещание в avionics_bus
  sensors:
    build: ./sensors
    depends_on:
      - controllers
    networks: [ avionics_bus ]

  # 🧠 Контроллеры — получают данные от сенсоров и принимают решения
  # Протокол: псевдо-CAN (UDP)
  controllers:
    build: ./controllers
    depends_on:
      - actuators
    networks: [ avionics_bus ]

  # ⚙️ Исполнительные механизмы — приводят в действие команды (закрылки, шасси и т.д.)
  # Протокол: псевдо-CAN (UDP), команды от контроллеров
  actuators:
    build: ./actuators
    networks: [ avionics_bus ]

  # 💀 Злоумышленник — может сканировать сети или проводить атаки
  # Доступ к control и public сетям
  # attacker_node:
  #   build: ./attacker_node
  #   networks:
  #     - public_access
  #     - control_network
  #   restart: "no"  # Запускается вручную при тесте

  # 🕵️ Сниффер — слушает avionics_bus
  # Может логгировать UDP пакеты и выявлять уязвимости/аномалии
  # sniffer:
  #   build: ./sniffer
  #   networks:
  #     - avionics_bus
  #   restart: unless-stopped

  security_scanner:
    build: ./security_scanner
    networks:
      - avionics_bus       # сканирует сенсоры, контроллеры, шлюз
      - control_network    # сканирует тех. сервер и интерфейс пилота
    depends_on:
      - avionics
      - pilot_interface
      - maintenance_server
      - ife_server
    restart: "no"

networks:
  # CAN-подобная сетевая шина (эмулируется через bridge + UDP)
  avionics_bus:
    driver: bridge
    name: avionics_bus_net

  # Служебная внутренняя сеть (эквивалент ARINC 664 / AFDX)
  control_network:
    driver: bridge
    name: control_net

  # Пассажирская сеть — доступ к развлечениям и интернету
  public_access:
    driver: bridge
    name: public_net
